### ISSUE TITLE
Add another failure condition

### ISSUE THREAD

**Issue by RumiaTouhou** [yorkpirates/Assessment-2-Game#27]
1. the area of the chest is too big (it takes effect before the ship has even touched the edge of the chest)
2. unable to tell if colleges are enemy or friendly (there are no advance system prompts and all ships and buildings are unattackable, which is very unfriendly to new players)
3. the maximum number of bullets that can be present on the screen at the same time should be adjusted to a suitable value, or a different mechanism (for example, the 'survival time' of each bullet) should be used (For example, after the player has activated the powerup "shoot all 8 directions", the bullets may disappear when fired in succession. However, if this value is not set, the bullets will fly around outside the player's field of vision, allowing the player to destroy buildings that not intended to destroy without knowing it)
4. cannot test lose in the current stage, as ship combat has not been implemented so the player won't die anyway

**Comment by RumiaTouhou** [comment]
5. It would be better to add another failure condition: the number of coins the player has < the price of the bullet pack and the number of bullets the player has = 0, and the current mission is to destroy a certain college. In this case, the player should be automatically ruled a failure.

**Comment by dom-hall** [comment]
3. Survival time is fixed

**Comment by dom-hall** [comment]
5. To Do

**Comment by dom-hall** [comment]
Money can be collected from chests to having no money is not an automatic loss.
